channels:
- conda-forge
dependencies:
- python
- jupyter
- pyiron_base =0.5.6
- fenics =2019.1.0
- mshr =2019.1.0
- matplotlib
- seaborn
- pip
- pip:
  - git+https://github.com/pyiron/pyiron_base.git@dynamic
